name: Delete Release

on:
  delete

jobs:
  delete-release:
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/trial/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: Release ${{ github.ref_name }}